name: Automatic OSINT Data Collector

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Récupérer le code du dépôt
      uses: actions/checkout@v4

    - name: Configurer Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Exécuter le script de collecte OSINT
      run: python collector.py

    - name: Sauvegarder et publier les nouvelles données
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin main
          git pull --rebase origin main
          git add data_feed.json
          git diff-index --quiet HEAD || (git commit -m "Auto-update OSINT feed data [skip ci]" && git push)
